<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>$(WindowsTfm)</TargetFramework>
    <TargetPlatformMinVersion>$(WindowsMinVersion)</TargetPlatformMinVersion>
    <SupportedOSPlatformVersion>$(WindowsMinVersion)</SupportedOSPlatformVersion>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <RootNamespace>HushMusic.Playback.Tests</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit.v3" />
    <PackageReference Include="xunit.runner.visualstudio" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\HushMusic.Playback\HushMusic.Playback.csproj" />
  </ItemGroup>

</Project>
